Traceback (most recent call last):
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../modules/solverbase.py", line 641, in _map
    assert len(indices) == len(x), "_map: indices and values have different length"
AssertionError: _map: indices and values have different length

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launchTillage.py", line 8, in <module>
    results_dir = mainTillage.XcGrowth(25.5, 30.,0,spellData )
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/mainTillage.py", line 106, in XcGrowth
    s = scenario_setup.create_soil_model(usemoles = usemoles, 
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../inputDataTillage/scenario_setup.py", line 356, in create_soil_model
    s = setupOther(s, p_mean_)
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../inputDataTillage/scenario_setup.py", line 407, in setupOther
    s.initializeProblem(s.maxDt)
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../modules/solverbase.py", line 309, in initializeProblem
    self.cellsVertex = self._map(comm.gather(self.base.getCells(),root=0), 2, np.int64)
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../modules/solverbase.py", line 645, in _map
    raise Exception
Exception
mpirun: Forwarding signal 18 to job
slurmstepd: error: *** JOB 30221 ON node15 CANCELLED AT 2024-08-09T10:08:19 ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
mpirun: abort is already in progress...hit ctrl-c again to forcibly terminate

[node15:2494144] *** Process received signal ***
[node15:2494144] Signal: Segmentation fault (11)
[node15:2494144] Signal code: Address not mapped (1)
[node15:2494144] Failing at address: 0x30
[node15:2494144] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7f13477c7090]
[node15:2494144] [ 1] /opt/openmpi/4.1.4/lib/openmpi/mca_pmix_pmix3x.so(PMIx_Finalize+0x518)[0x7f1344f57158]
[node15:2494144] [ 2] /opt/openmpi/4.1.4/lib/openmpi/mca_pmix_pmix3x.so(pmix3x_client_finalize+0x3aa)[0x7f1344f1e6fa]
[node15:2494144] [ 3] /opt/openmpi/4.1.4/lib/openmpi/mca_ess_hnp.so(+0x4d56)[0x7f1347511d56]
[node15:2494144] [ 4] /opt/openmpi/4.1.4/lib/openmpi/mca_ess_hnp.so(+0x4df5)[0x7f1347511df5]
[node15:2494144] [ 5] /lib/x86_64-linux-gnu/libevent_core-2.1.so.7(+0x1ce5e)[0x7f1347992e5e]
[node15:2494144] [ 6] /lib/x86_64-linux-gnu/libevent_core-2.1.so.7(event_base_loop+0x52f)[0x7f13479936ff]
[node15:2494144] [ 7] mpirun(+0x14a1)[0x5568c028d4a1]
[node15:2494144] [ 8] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f13477a8083]
[node15:2494144] [ 9] mpirun(+0x11fe)[0x5568c028d1fe]
[node15:2494144] *** End of error message ***
