Traceback (most recent call last):
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../modules/solverbase.py", line 641, in _map
    assert len(indices) == len(x), "_map: indices and values have different length"
AssertionError: _map: indices and values have different length

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launchTillage.py", line 8, in <module>
    results_dir = mainTillage.XcGrowth(25.5, 30.,0,spellData )
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/mainTillage.py", line 106, in XcGrowth
    s = scenario_setup.create_soil_model(usemoles = usemoles, 
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../inputDataTillage/scenario_setup.py", line 356, in create_soil_model
    s = setupOther(s, p_mean_)
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../inputDataTillage/scenario_setup.py", line 407, in setupOther
    s.initializeProblem(s.maxDt)
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../modules/solverbase.py", line 309, in initializeProblem
    self.cellsVertex = self._map(comm.gather(self.base.getCells(),root=0), 2, np.int64)
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../modules/solverbase.py", line 645, in _map
    raise Exception
Exception
mpirun: Forwarding signal 18 to job
slurmstepd: error: *** JOB 30220 ON node14 CANCELLED AT 2024-08-08T18:16:39 ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 9 with PID 3293153 on node node14 exited on signal 15 (Terminated).
--------------------------------------------------------------------------
